/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as ScanTanqueIdRouteImport } from './routes/scan.$tanqueId'
import { Route as ApiIngestaRouteImport } from './routes/api.ingesta'
import { Route as AppPurgasRouteImport } from './routes/_app.purgas'
import { Route as AppExtractoRouteImport } from './routes/_app.extracto'
import { Route as AppChequeosRouteImport } from './routes/_app.chequeos'
import { Route as AppAgendaRouteImport } from './routes/_app.agenda'
import { Route as AppAdminQrPrintRouteImport } from './routes/_app.admin.qr-print'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ScanTanqueIdRoute = ScanTanqueIdRouteImport.update({
  id: '/scan/$tanqueId',
  path: '/scan/$tanqueId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestaRoute = ApiIngestaRouteImport.update({
  id: '/api/ingesta',
  path: '/api/ingesta',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPurgasRoute = AppPurgasRouteImport.update({
  id: '/purgas',
  path: '/purgas',
  getParentRoute: () => AppRoute,
} as any)
const AppExtractoRoute = AppExtractoRouteImport.update({
  id: '/extracto',
  path: '/extracto',
  getParentRoute: () => AppRoute,
} as any)
const AppChequeosRoute = AppChequeosRouteImport.update({
  id: '/chequeos',
  path: '/chequeos',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminQrPrintRoute = AppAdminQrPrintRouteImport.update({
  id: '/admin/qr-print',
  path: '/admin/qr-print',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/agenda': typeof AppAgendaRoute
  '/chequeos': typeof AppChequeosRoute
  '/extracto': typeof AppExtractoRoute
  '/purgas': typeof AppPurgasRoute
  '/api/ingesta': typeof ApiIngestaRoute
  '/scan/$tanqueId': typeof ScanTanqueIdRoute
  '/admin/qr-print': typeof AppAdminQrPrintRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/agenda': typeof AppAgendaRoute
  '/chequeos': typeof AppChequeosRoute
  '/extracto': typeof AppExtractoRoute
  '/purgas': typeof AppPurgasRoute
  '/api/ingesta': typeof ApiIngestaRoute
  '/scan/$tanqueId': typeof ScanTanqueIdRoute
  '/': typeof AppIndexRoute
  '/admin/qr-print': typeof AppAdminQrPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/chequeos': typeof AppChequeosRoute
  '/_app/extracto': typeof AppExtractoRoute
  '/_app/purgas': typeof AppPurgasRoute
  '/api/ingesta': typeof ApiIngestaRoute
  '/scan/$tanqueId': typeof ScanTanqueIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/qr-print': typeof AppAdminQrPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agenda'
    | '/chequeos'
    | '/extracto'
    | '/purgas'
    | '/api/ingesta'
    | '/scan/$tanqueId'
    | '/admin/qr-print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/agenda'
    | '/chequeos'
    | '/extracto'
    | '/purgas'
    | '/api/ingesta'
    | '/scan/$tanqueId'
    | '/'
    | '/admin/qr-print'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/agenda'
    | '/_app/chequeos'
    | '/_app/extracto'
    | '/_app/purgas'
    | '/api/ingesta'
    | '/scan/$tanqueId'
    | '/_app/'
    | '/_app/admin/qr-print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiIngestaRoute: typeof ApiIngestaRoute
  ScanTanqueIdRoute: typeof ScanTanqueIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/scan/$tanqueId': {
      id: '/scan/$tanqueId'
      path: '/scan/$tanqueId'
      fullPath: '/scan/$tanqueId'
      preLoaderRoute: typeof ScanTanqueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingesta': {
      id: '/api/ingesta'
      path: '/api/ingesta'
      fullPath: '/api/ingesta'
      preLoaderRoute: typeof ApiIngestaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/purgas': {
      id: '/_app/purgas'
      path: '/purgas'
      fullPath: '/purgas'
      preLoaderRoute: typeof AppPurgasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/extracto': {
      id: '/_app/extracto'
      path: '/extracto'
      fullPath: '/extracto'
      preLoaderRoute: typeof AppExtractoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chequeos': {
      id: '/_app/chequeos'
      path: '/chequeos'
      fullPath: '/chequeos'
      preLoaderRoute: typeof AppChequeosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/qr-print': {
      id: '/_app/admin/qr-print'
      path: '/admin/qr-print'
      fullPath: '/admin/qr-print'
      preLoaderRoute: typeof AppAdminQrPrintRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppChequeosRoute: typeof AppChequeosRoute
  AppExtractoRoute: typeof AppExtractoRoute
  AppPurgasRoute: typeof AppPurgasRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminQrPrintRoute: typeof AppAdminQrPrintRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppChequeosRoute: AppChequeosRoute,
  AppExtractoRoute: AppExtractoRoute,
  AppPurgasRoute: AppPurgasRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminQrPrintRoute: AppAdminQrPrintRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiIngestaRoute: ApiIngestaRoute,
  ScanTanqueIdRoute: ScanTanqueIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
